config/routes.rb
Rails.application.routes.draw do

  resources :todoodles do
    resources :tasks
  end
  resources :user_sessions
  resources :users

  root 'todoodles#index'

end

app/models/task.rb
class Task < ActiveRecord::Base

belongs_to :todoodle
validates_presence_of :item

end

app/models/todoodle.rb
class Todoodle < ActiveRecord::Base

has_many :tasks
belongs_to :user
validates_presence_of :title

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |f|
    f.login_field = :name
  end
has_many :todoodles, dependent: :destroy

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception
helper_method :current_user
before_action :current_user

private
  def current_user_session
    if defined?(@current_user_session)
        return @current_user_session
      else
        @current_user_session = UserSession.find
    end
  end

  def current_user
    if defined?(@current_user)
      return @current_user
    else
      @current_user = current_user_session && current_user_session.record
    end
  end

  def require_user
    unless current_user
      flash[:alert]="You have to be logged in"
      redirect_to root_url, [:alert]=>"You've deleted that list!"
    end
  end

  def require_no_user
    if current_user
        flash[:alert]="You are already logged in"
        redirect_to root_url
    end
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

def new
  @task = Task.new
  @task.completed=false
  @todoodle = Todoodle.find(params[:todoodle_id])
end

def create
  @todoodle = Todoodle.find(params[:todoodle_id])
  @task = @todoodle.tasks.new(new_task_params)
  @task.completed=false
  if @task.save
    flash[:notice]="...Another Task ToDoodle!"
    redirect_to root_url
  else
    flash[:notice]="Try again. Something didn't work right. :("
    render :new
  end

end

def edit
  @task = Task.find(params[:id])
end

def update
  @task = Task.find(params[:id])
  @task.update_attributes(completed:true)
  @task.save!
  flash[:notice]="That's done! Great Job!"

  redirect_to root_url
end



private

def new_task_params
  params.require(:task).permit(:item)
end


end

app/controllers/todoodles_controller.rb
class TodoodlesController < ApplicationController

def new
  @user = current_user
  @todoodle = @user.todoodles.build
end

def create
  @todoodle = Todoodle.new(new_todoodle_params)
  @todoodle.user = current_user
  if @todoodle.save
    flash[:notice]="A New ToDoodle!"
    redirect_to root_url
  else
    flash[:notice]="Try again. Something didn't work right. :("
    render :new
  end
end

def edit
  @todoodle = Todoodle.find(params[:id])
end


def index
  @todoodles = Todoodle.all
  @user = current_user
end

def destroy
  @todoodle = Todoodle.find(params[:id])
  @todoodle.destroy
  redirect_to root_url
end


private

def new_todoodle_params
  params.require(:todoodle).permit(:title)
end


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
    before_action :require_user, only: [:destroy]

    def new
      @user_session = UserSession.new
      end

    def create
      @user_session = UserSession.new(user_session_params)
        if @user_session.save
          redirect_to root_url
        else
          flash[:notice]="Try again. Something didn't work right. :("
          redirect_to new_user_session_path
        end
    end

    def destroy
      @user_session = UserSession.find
      @user_session.destroy
      redirect_to root_url
    end

    private
      def set_user_session
        @user_session = UserSession.find(params[:id])
      end

      def user_session_params
        params.require(:user_session).permit(:name, :password)
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @todoodles=Todoodles.all
end

def new
  @user=User.new
end

def create
  @user = User.new(newguy_params)
  if @user.save
    flash[:notice]="Great Job! Let's make some lists!"
    redirect_to root_url
  else
    flash[:notice]="Hm. Something went wrong. Try again"
    redirect_to new_user_path
  end

end

private

def newguy_params
  params.require(:user).permit(:name,:email,:password,:password_confirmation)
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todoodles_helper.rb
module TodoodlesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoodles</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

      <div class = "jumbotron">
        <% if current_user%>
          <h3>Welcome, <%=@current_user.name.upcase%>!</h3>
          <h1 class="page-title">
            <%=link_to image_tag("Todoodles-icon.png", :style=>"width:100px;")+"oDoodles!", root_url%>
          </h1>
            <%=link_to "Add ToDoodle", new_todoodle_path, class: "btn btn-danger btn-lg"%>
            <%=link_to "Log Out", user_session_path(@current_user), :method => :delete, class: "btn btn-primary btn-lg"%>

        <%else%>
          <h1 class="page-title">
            <%=link_to image_tag("Todoodles-icon.png", :style=>"width:100px;")+"oDoodles!", root_url%>
          </h1>
          <%=link_to "Sign Up!", new_user_path, class: "btn btn-danger btn-lg"%>
          <%=link_to "Log in!", new_user_session_path, class: "btn btn-primary btn-lg"%>
        <%end%>
      </div>

    <% if flash[:notice] %>
      <div class = "container">
        <h2><%= flash[:notice] %></h2>
      </div>
    <%end%>

    <div class="container">
    <%= yield %>
    </div>

  </body>
  <br>
  <footer>
      <nav class="navbar navbar-default navbar-fixed-bottom" id="footer">
        <p>A silly To-Do list tracking application by <a href="http://uptobuildingcode.blogspot.com/">Ben Doane</a> for <a href="http://theironyard.com/locations/indianapolis/">The Iron Yard</a>.</p>
      </nav>
  </footer>
</html>

app/views/tasks/new.html.erb
<div class="container">

  <%=bootstrap_form_for([@todoodle, @task]) do |t|%>
    <div class="field">
    <%=t.text_field :item%>
  </div>
  <div class="actions">
    <%= t.submit "Add Task", :class => "btn btn-primary" %>
  </div>
  <%end%>

</div>

app/views/todoodles/edit.html.erb
<div class="container">

  <h2><%=@todoodle.title%></h2>
  <%=bootstrap_form_for(@todoodle) do |d|%>
  <div class="field">
    <div id ="desc">
      <%= d.text_field :description, placeholder: "Quick, short reminder", :maxlength => "20" %>
    </div>
  </div>
  <%end%>

</div>

app/views/todoodles/index.html.erb
<div class = "container">
  <div class = "page-goodies">
      <% if current_user%>

        <%if current_user.todoodles.empty?%>
          <h3>You currently have no ToDoodles!</h3>
          <h5>You can add one with the button above</h5>
        <%else%>
          <%current_user.todoodles.each_slice(4) do |four|%>
            <div class="row">
              <% four.each do |t|%>
                <div class="col-xs-3">
                  <div class="item-tab">
                    <h2><%=t.title%></h2>
                    <h5>
                      <%if t.tasks%>
                        <%t.tasks.each do |task|%>
                          <% if task.completed==false%>
                            <%=link_to todoodle_task_path(task.todoodle_id,task.id), :method=>:put do%>
                              <i class="glyphicon glyphicon-ok-circle"></i>
                            <%end%>
                          <%else%>
                            <i class="glyphicon glyphicon-ok"></i>
                          <%end%>
                          <%=task.item%>
                          <br>
                        <%end%>
                        <br>
                      <%end%>
                    </h5>
                    <%=link_to "add tasks", new_todoodle_task_path(t), class: "btn btn-primary btn-sm"%>
                    <%=link_to todoodle_path(t), :class => "btn btn-danger delete", :method=>:delete do%>
                      <i class="glyphicon glyphicon-trash"></i>
                      <%end%>
                  </div>
                </div>
                <%end%>
              </div>
          <%end%>
          <%end%>


      <%else%>
        <div class = "container">
          <h2>Welcome to ToDoodles!</h2>
          <p>ToDoodles is a fun way for you to enter your "to do" lists, and keep track of what you've accomplished!</p>
          <p>Sign up to start Todoodling today!</p>
        </div>
      <%end%>

  </div>
</div>

app/views/todoodles/new.html.erb
<div class = "container">
  <h1>Add ToDoodle</h1>

  <%=bootstrap_form_for(@todoodle) do |d|%>
    <% if @todoodle.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @todoodle.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= d.text_field :title, placeholder: "What's yer list called?", :maxlength => "12" %>
    </div>

    <div class="actions">
      <%= d.submit "Add", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/user_sessions/new.html.erb
<div class = "container">

  <%=form_for @user_session do |s|%>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user_session.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= s.label :name %><br>
      <%= s.text_field :name, placeholder:"Your name" %>
    </div>
    <div class="field">
      <%= s.label :password %><br>
      <%= s.password_field :password, placeholder: "Password" %>
    </div>
    <br>
    <div class="actions">
      <%= s.submit "Login" %>
    </div>
  <% end %>
</div>

app/views/users/_signup.html.erb
<%=form_for(@user) do |f|%>

    <div class="field">
      <%= f.label :name%>
      <%= f.text_field :name%>
    </div>
    <br>
    <div class="field">
      <%= f.label :email%>
      <%= f.text_field :email%>
    </div>
    <br>
    <div class="field">
      <%= f.label :password%>
      <%= f.password_field :password%>
    </div>
    <br>
    <div class="field">
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation%>
    </div>
    <br>
    <%= f.submit%>
  <%end%>

app/views/users/new.html.erb
<div class = "container">
  <h1>Sign up!</h1>
  <h4>So we can get to crackin'!<h4>
  <%=render "signup"%>
</div>